#!/bin/bash

# check all argumets were passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <namespace> <node or pod> "
    exit 1
fi

# Define command-line arguments
NAMESPACE=$1
RESOURCE_TYPE=$2

# Retrieve resource usage statistics from Kubernetes
echo "Resource, Namespace, Name, CPU, Memory"

kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console  
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
